28.02
htmlacademy-htmlcss/1711441-sedona-30 pull request #10
Opened 2021-02-28 17:42 UTC by Nina202087

2021-03-01 16:00 UTC, Nina202087 commented
01.03

2021-03-02 07:53 UTC, YaroslavWD requested changes
https://take.ms/VpRgH Здесь тебе нужна еще одна обертка для всего контента, и относительно который ты будешь это позиционировать. 
Так же давай добавляй карту уже, хотя бы просто изображение, и позиционируй футер относительно карты.

2021-03-02 07:53 UTC, YaroslavWD commented on css/style.css
> +  width: 1200;
Проверь в браузере работает ли это свойство?

2021-03-02 07:53 UTC, YaroslavWD commented on css/style.css
> +}
Не должно быть пустых свойств

2021-03-02 07:53 UTC, YaroslavWD commented on css/style.css
> +  width: 1200;
![image](https://user-images.githubusercontent.com/37155263/109614832-f43c6480-7b54-11eb-885d-93f4ba289493.png)

2021-03-02 07:53 UTC, YaroslavWD commented on css/style.css
Шапка не совпадает по pixel perfect, подбери прямо в браузере нужные свойства
https://take.ms/F2A64

2021-03-02 19:07 UTC, Nina202087 commented
03.03

2021-03-05 06:15 UTC, merged